version: '3'

services:
  primary:
    container_name: "isucon-training-primary"
    privileged: true # use for systemd execute.
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
      - type: volume
        source: home-isucon
        target: /home/isucon
        read_only: false
      - type: volume
        source: home-isucon-admin
        target: /home/isucon-admin
        read_only: false
      - type: volume
        source: root-isucon
        target: /root/isucon
        read_only: false
      - type: volume
        source: root-isucon-admin
        target: /root/isucon-admin
        read_only: false
      - type: bind
        source: ./Makefile
        target: /root/Makefile
      - type: bind
        source: ./Setup
        target: /root/Setup
    ports: [ 2222:22 ]
    extra_hosts:
      - "localhost:127.0.0.1"
      - "isucondition-1.t.isucon.dev:127.0.0.11"
      - "isucondition-2.t.isucon.dev:127.0.0.12"
      - "isucondition-3.t.isucon.dev:127.0.0.13"

volumes:
  root-isucon:
  root-isucon-admin:
  home-isucon:
  home-isucon-admin: